app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
admin:
    path:     /admin
    defaults: { _controller: AppBundle:Admin:index }    
manage:
    path:     /manage
    defaults: { _controller: AppBundle:Manage:index  } 
manage_edit:
    path:     /manage/edit/{workflowid}
    defaults: { _controller: AppBundle:Manage:edit  } 
manage_create:
    path:     /manage/create/
    defaults: { _controller: AppBundle:Manage:create  }
manage_update:
    path:     /manage/update/
    defaults: { _controller: AppBundle:Manage:update  } 
manage_delete:
    path:     /manage/delete/
    defaults: { _controller: AppBundle:Manage:delete  }      
                              
monitoring:
    path:     /monitoring
    defaults: { _controller: AppBundle:Monitoring:index }     
submitting:
    path:     /submitting
    defaults: { _controller: AppBundle:Submitting:index }
transcoders:
    path:     /transcoders
    defaults: { _controller: AppBundle:Transcoders:index }                
