app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
admin:
    path:     /admin
    defaults: { _controller: AppBundle:Admin:index }    
manage:
    path:     /manage
    defaults: { _controller: AppBundle:Manage:index } 
monitoring:
    path:     /monitoring
    defaults: { _controller: AppBundle:Monitoring:index }     
submitting:
    path:     /submitting
    defaults: { _controller: AppBundle:Submitting:index }
transcoders:
    path:     /transcoders
    defaults: { _controller: AppBundle:Transcoders:index }                
