<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RPublishingRuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RPublishingRuleRepository extends EntityRepository
{
	
	
	/**
	 * Filter ruleType on a given id
	 *
	 *
	 */
	public function getRuleTypeByWorkflowId($id)
	{
	
		$qb = $this->createQueryBuilder('a');
		$qb->where('a.workflow = :id')->setParameter('id', $id);
		$qb->orderBy('a.ruleOrder' , 'ASC') ;
		return $qb;
	}
	
	
	public function toString(){
		
		return 'in there' ;
	}
	
	
}
